# /opt/monitoring/loki-config.yaml
auth_enabled: false

# -----------------------------------------------------------------------------
# СЕРВЕР
# -----------------------------------------------------------------------------
server:
  http_listen_port: 3100
  log_level: info
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  grpc_server_max_recv_msg_size: 4_194_304   # 4 MiB
  grpc_server_max_send_msg_size: 4_194_304

# -----------------------------------------------------------------------------
# ОБЩИЕ НАСТРОЙКИ (ring, хранилище)
# -----------------------------------------------------------------------------
common:
  path_prefix: /loki                 # базовый каталог (чэнки, индексы, WAL…)
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory                # single-node
  storage:                           # файловое хранилище на том же диске
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory:  /loki/rules

# -----------------------------------------------------------------------------
# INGESTER
# -----------------------------------------------------------------------------
ingester:
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_chunk_age: 1h
  wal:                               # WAL обязателен для TSDB-backend
    enabled: true
    dir: /loki/wal

# -----------------------------------------------------------------------------
# СХЕМА / ИНДЕКСЫ
# -----------------------------------------------------------------------------
schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb                    # вместо boltdb-shipper
      object_store: filesystem
      schema: v13                    # актуальная версия
      index:
        prefix: index_
        period: 24h

# -----------------------------------------------------------------------------
# ХРАНИЛИЩЕ (TSDB + кеш)
# -----------------------------------------------------------------------------
storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location:        /loki/tsdb-cache
  filesystem:
    directory: /loki/chunks         # сами чэнки

# -----------------------------------------------------------------------------
# ЛИМИТЫ
# -----------------------------------------------------------------------------
limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h   # 7 дней
  retention_period:         168h
