name: Build and Deploy Django App

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        run: |
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          echo "Extracted version: ${GITHUB_REF#refs/tags/v}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: django-demo
          file: django-demo/Dockerfile
          push: true
          tags: cybersec7007/devops-infra:${{ steps.get_version.outputs.version }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.13.2'

      - name: Deploy to Kubernetes
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig.yaml
          helm upgrade django-demo ./django-demo/helm-chart \
            --install \
            --namespace default \
            --create-namespace \
            --set image.repository=cybersec7007/devops-infra \
            --set image.tag=${{ needs.build.outputs.version }} \
            --wait \
            --atomic \
            --kubeconfig kubeconfig.yaml
